### ISSUE TITLE
Terminal ERROR

### ISSUE THREAD

**Issue by LongTermPerception** [miurla/babyagi-ui#11]
When running BabyAgi-UI, noticed in the terminal providing this error.

```
wait  - compiling /api/enrich (client and server)...
event - compiled successfully in 48 ms (280 modules)
error - [RangeError: Invalid status code: 0] {
  code: 'ERR_HTTP_INVALID_STATUS_CODE'

```

Than later on I may get a error like this

```
error - [RangeError: Invalid status code: 0] {
  code: 'ERR_HTTP_INVALID_STATUS_CODE'
}
```

Any clarification if this is a major issue or not would be greatly appreciated, also is there way for it to continue or save its previous sessions?

**Comment by miurla** [comment]
Is the Pinecone index already created?
If not, please create it and then try building.

Link to a similar issue: https://github.com/miurla/babyagi-ui/issues/4

**Comment by JAMadison** [comment]
![image](https://user-images.githubusercontent.com/88359049/236640858-b9e9039c-f1f9-48b2-a516-72cb2a1d3190.png)
I have made sure to create an Index on Pinecone as well as an API key. I have also set my chatGPT API key and verified my .dev file is accurate with all my information. I still receive this error, any ideas?

**Comment by miurla** [comment]
@LongTermPerception 
The error occurs when the `table name` specified in the env file and the Pinecone `index name` are different. 
Could you please check them once again?

**Comment by LongTermPerception** [comment]
I've changed the requested values of the `table name` to match the `index name`, but still getting invalid status

<img width="1154" alt="CODE" src="https://user-images.githubusercontent.com/78527368/236758112-87b41265-3ad3-4ca2-a8df-de95e73f5fff.png">

That's the .env file

<img width="1440" alt="PINE" src="https://user-images.githubusercontent.com/78527368/236758208-c34446ce-0a79-4761-b172-78e59bb79cf5.png">


pinecone index

**Comment by kvk-code** [comment]
I think you need to get rid of double-quotes("value") around the values bud..

**Comment by miurla** [comment]
Thank you for checking. The index name seems to be good. Since the Dimensions is set to 3000, could you please try changing it to 1536 and test it?

https://github.com/miurla/babyagi-ui/blob/main/public/pinecone-setup.png

**Comment by LongTermPerception** [comment]
> Thank you for checking. The index name seems to be good. Since the Dimensions is set to 3000, could you please try changing it to 1536 and test it?
> 
> [Reference setting](https://github.com/miurla/babyagi-ui/blob/main/public/pinecone-setup.png) (https://github.com/miurla/babyagi-ui#-getting-started: Step4)

Issue has been resolved!
Not receiving the terminal errors anymore, appreciate the response.

Also will you be working towards adding the feature of previous chats along the left navigation bar?
And will it be possible to pause and continue from last session?

**Comment by LongTermPerception** [comment]
> Thank you for checking. The index name seems to be good. Since the Dimensions is set to 3000, could you please try changing it to 1536 and test it?
> 
> [Reference setting](https://github.com/miurla/babyagi-ui/blob/main/public/pinecone-setup.png) (https://github.com/miurla/babyagi-ui#-getting-started: Step4)

Issue has been resolved!
Not receiving the terminal errors anymore, appreciate the response.

Also will you be working towards adding the feature of previous chats along the left navigation bar?
And will it be possible to pause and continue from last session?

**Comment by miurla** [comment]
Glad to see it resolved!

> Also will you be working towards adding the feature of previous chats along the left navigation bar?

Yes, We are planning to display the execution history like ChatGPT! 

> And will it be possible to pause and continue from last session?

Currently, we don't support pausing sessions.
We are also considering implementing that feature.
