### ISSUE TITLE
BabyDeer + GPT-4 >> ERROR_CREATING_TASKS

### ISSUE THREAD

**Issue by regismvargas** [miurla/babyagi-ui#118]
I received the message "ERROR_CREATING_TASKS" when trying to use GPT-4. GPT-3 it's working fine.

![image](https://github.com/miurla/babyagi-ui/assets/46408091/176b1150-5deb-4525-8a14-8b1e6828e2f7)

**Comment by miurla** [comment]
In this case, the issue is mostly caused by the API key not having access to GPT-4. Do you have the access rights?
https://platform.openai.com/docs/models/gpt-4

**Comment by miurla** [comment]
GPT-4 has been released to everyone, so I will close this issue.
