### ISSUE TITLE
Adapts to unofficial api

### ISSUE THREAD

**Issue by gngpp** [miurla/babyagi-ui#120]
Hello, do you plan to adapt to the unofficial API？ (which is actually a proxy for the official web version of the API) , I currently bypass Cloudflare to call the API, support email password login, API documentation here, you can build your own tests (I can also provide API service tests) 

project: https://github.com/gngpp/opengpt
api doc: https://github.com/gngpp/opengpt/blob/main/doc/rest.http

**Comment by miurla** [comment]
Hi @gngpp, thanks for the suggestion. 
Currently, we don’t have plans to adopt the unofficial API. 
In what use cases would this API be necessary?

**Comment by gngpp** [comment]
> Hi @gngpp, thanks for the suggestion.嗨，感谢您的建议。 Currently, we don’t have plans to adopt the unofficial API.目前，我们没有采用非官方 API 的计划。 In what use cases would this API be necessary? 在哪些用例中需要此 API？

Because it's free, and the model is a bit smarter than the official API, reference projects
: https://github.com/pengzhile/pandora
