### ISSUE TITLE
WebBrowser Issue After Update

### ISSUE THREAD

**Issue by ABYSSTENSOR** [miurla/babyagi-ui#123]
hi,
I updated last version yesterday
But, i realize  errors : 

With google chrome:
First : in cmd when in use : "Fast Refresh had to perform a full reload"
Second : New IntroGuide.tsx] menu is not visible in chrome but sidebar menu with istoric is okay
With Firefox:
First : No problem in cmdlog  : No "Fast Refresh had to perform a full reload" anymore
Second: New [IntroGuide.tsx] menu is  visible but sidebar menu with historic text is not visible

any conflit UI ?
Thanx do reporting solution

AbyssTensor

**Comment by miurla** [comment]
Hi @ABYSSTENSOR, 
please check the following items:

- The IntroGuide menu is displayed when the execution history is less than 5.
  - https://github.com/miurla/babyagi-ui/blob/main/src/components/Agent/Agent.tsx#L431
- The history is stored locally in the browser
  - The history varies by browser
- The error "Fast Refresh had to perform a full reload" depends on the local development environment
   - https://stackoverflow.com/a/74640821

**Comment by ABYSSTENSOR** [comment]
you make my day boss
