### ISSUE TITLE
How can translate to spanish this strings (Modelo: OpenAI gpt-3.5-turbo | Agente: BabyDeerAGI 🦌)

### ISSUE THREAD

**Issue by johnfelipe** [miurla/babyagi-ui#128]
| ID | Status | Task  | Tool | Dependency | 

Failed to generate text.

All tasks completed!

That some strings in web page and txt downloaded not translated to spanish
Tell me where and how can PR with translated strings

**Comment by miurla** [comment]
The steps are as follows:

1. Add a value to the corresponding json in public/locales/en.
2. Change to localizing with the `translate` function.
3. Use the `npm run translate` command to automatically convert other languages using en as the source.

Reference commit:
https://github.com/miurla/babyagi-ui/pull/121/commits/48f884ed852f433ed41b0bd86e656af3f4a3ebb2

**Comment by johnfelipe** [comment]
sudo su
	cd
	curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -

	sudo apt-get install -y nodejs

	git clone https://github.com/miurla/babyagi-ui

	cd babyagi-ui

	npm install

That is my steps, can u elaborate for future translation to all lang, i want to contribute with that, but i need all steps, commands, path, etc....

**Comment by johnfelipe** [comment]
Only until npm start
That because I have all in vercel deployment

**Comment by johnfelipe** [comment]
how can contribute with translation then?

**Comment by miurla** [comment]
Have you set up your local build environment? 
You’ll need to use the npm command. 
https://github.com/miurla/babyagi-ui/issues/128#issuecomment-1625584157

Once you're ready, the procedure is as previously guided. 
https://github.com/miurla/babyagi-ui/issues/128#issuecomment-1625423278"

**Comment by johnfelipe** [comment]
Can u generate MD file with step by step for contribute with translation to Spanish all strings not translated
Because this step

Change to localizing with the translate function.

Is not knowledge to me

**Comment by miurla** [comment]
@johnfelipe 
I appreciate your enthusiasm. However, since this application supports over 40 languages, it’s best to handle it with automatic translation. Once I’m done with #130, I’ll handle it.

Would you mind contributing by correcting any parts in Spanish where the nuance is off, if you don’t mind? The file is below.
https://github.com/miurla/babyagi-ui/tree/main/public/locales/en

**Comment by johnfelipe** [comment]
@miurla can u help me now, with steps, workflow, edition, commands for contribute with translation?

**Comment by miurla** [comment]
> can u help me now, with steps, workflow, edition, commands for contribute with translation?

Status of conversation on Discord

**Comment by miurla** [comment]
I have fixed 3. 2 is an error message, so I’ll leave it as it is. 1 has been made a separate issue.

https://github.com/miurla/babyagi-ui/issues/144
