### ISSUE TITLE
Replace search tool

### ISSUE THREAD

**Issue by miurla** [miurla/babyagi-ui#18]
SearpApi is expensive to use, replace with Duckduckgo.

**Comment by miurla** [comment]
I can't access api document.
Maybe the duckduckgo API isn't available.

https://www.reddit.com/r/duckduckgo/comments/xm6ire/cannot_find_ddg_instant_answers_api_documentation/

**Comment by ilyazub** [comment]
Thanks for your work! We (@serpapi) would love to sponsor your project.

Let us know what do you think.

**Comment by miurla** [comment]
@ilyazub 

Wow, Serpapi team! Thank you for the offer. 

I believe that search tools are extremely important for autonomous agents. I would like to consider adding other options not only in terms of cost but also in other factors. What are your team's thoughts on the development of those options?

**Comment by ilyazub** [comment]
@miurla Thanks for your kind feedback and considerations!

Please clarify what do you mean by "other factors" and "development of other options".

**Comment by miurla** [comment]
@ilyazub 

I apologize for the lack of clarity.

The original source of BabyAGI ([BabyBeeAGI](https://github.com/yoheinakajima/babyagi/blob/main/classic/BabyBeeAGI#L31)), which is at the core of this project, uses SerpAPI, and I tried to import it as faithfully as possible. Therefore, I don't know how the original code will be improved in the future, but I would like to be as responsive to changes as possible.

In the case of LangChain, there can be multiple search tool options within [the Agent's Tools](https://python.langchain.com/en/latest/modules/agents/tools.html ). In the future, as we enhance the tools, there is a non-zero possibility that we will increase the options.
Our project's core is the interface, so we don't prioritize expanding backend options, but we prioritize developers and users, so I consulted with you in advance.

It may be overthinking since the project has just started! If there are no issues with the above points, we would appreciate your sponsorship. Please consider it.

(P.S. I have a SerpAPI account, so it's convenient and useful for running LangChain!)

**Comment by ilyazub** [comment]
@miurla, having multiple search tools while being sponsored by SerpApi is totally fine. Let's discuss this via an email (_I'll send a message_).

**Comment by kvk-code** [comment]
> @ilyazub
> 
> I apologize for the lack of clarity.
> 
> The original source of BabyAGI ([BabyBeeAGI](https://github.com/yoheinakajima/babyagi/blob/main/classic/BabyBeeAGI#L31)), which is at the core of this project, uses SerpAPI, and I tried to import it as faithfully as possible. Therefore, I don't know how the original code will be improved in the future, but I would like to be as responsive to changes as possible.
> 
> In the case of LangChain, there can be multiple search tool options within [the Agent's Tools](https://python.langchain.com/en/latest/modules/agents/tools.html). In the future, as we enhance the tools, there is a non-zero possibility that we will increase the options. Our project's core is the interface, so we don't prioritize expanding backend options, but we prioritize developers and users, so I consulted with you in advance.
> 
> It may be overthinking since the project has just started! If there are no issues with the above points, we would appreciate your sponsorship. Please consider it.
> 
> (P.S. I have a SerpAPI account, so it's convenient and useful for running LangChain!)

Could we try using Google's Programmable Search Engine??Hope it gives better search results

**Comment by miurla** [comment]
@ilyazub 
Thank you for your understanding. 
I'll reply to your email.

**Comment by miurla** [comment]
Create a separate issue if search options become necessary.
