### ISSUE TITLE
where is updates or you move to another repo?

### ISSUE THREAD

**Issue by johnfelipe** [miurla/babyagi-ui#195]

**Comment by ehausen** [comment]
Also wondering, if this project is still active. 

If not, could someone perhaps recommend a more active repo, maybe by some other developer?

**Comment by johnfelipe** [comment]
Anyone?

**Comment by czerwinskilukasz1** [comment]
I'm also wondering.

**Comment by johnfelipe** [comment]
Anyone's

**Comment by miurla** [comment]
Hi there. AI Agents have been widely accepted and have transitioned from the experimental phase to the practical phase. This project's role of allowing users to easily try out BabyAGI (AI Agent) has ended. This repository will be archived.

As my next project, I'm developing an open-source project called Morphic. If you're interested, please give it a try: https://git.new/morphic
