### ISSUE TITLE
API

### ISSUE THREAD

**Issue by rohidjetha** [miurla/babyagi-ui#27]
Is it possible to have an API for it? So I can host this and use babyagi as an api

**Comment by miurla** [comment]
So you want to run BabyAGI as an API. There is a Node version in the original repository of BabyAGI, so it seems like a good idea to create an API based on that.
https://github.com/yoheinakajima/babyagi/tree/main/node

At first, I tried to create it with a single API, but I wanted to run it on Vercel, so I wrote the code using edge functions. However, I couldn't receive abort signal from the client and couldn't manage the loop on the server-side, so I changed it to be managed by the client. Also, it was necessary to use the user's OpenAI API key, and it was necessary to request the OpenAI endpoint directly from the client.

If you can create the API, please share it with us!
