### ISSUE TITLE
Updating Setup Procedure

### ISSUE THREAD

**Issue by yoshinorisano** [miurla/babyagi-ui#3]
Thank you for developing this interesting software. While testing babyagi-ui in my local environment, I encountered issues during execution of /api/context etc. The current [setup instructions](https://github.com/miurla/babyagi-ui#-getting-started) appear to be missing information regarding Pinecone configuration. After setting up an environment like below, the errors were resolved.

<img width="1439" alt="screenshot" src="https://user-images.githubusercontent.com/385102/235602537-90a64914-5f18-48a3-84db-ff48a1037f75.png">

**Comment by miurla** [comment]
Thank you for the report. On the app side, we set the following three environment variables for the Pinecone client. If the values are the same, it should work. If you know which value you modified to make it work, could you please let me know?

- PINECONE_API_KEY
- PINECONE_ENVIRONMENT
- NEXT_PUBLIC_TABLE_NAME

**Comment by yoshinorisano** [comment]
I have not made any modifications to the code or environment variables.
I simply created an index (baby-agi-test-table) on Pinecone **manually**, as shown in the attached screenshot above.

**Comment by yoshinorisano** [comment]
Thank you!
