### ISSUE TITLE
Request failed with status code 401

### ISSUE THREAD

**Issue by bobwatcherx** [miurla/babyagi-ui#32]
i have error in web 

Unhandled Runtime Error
```

AxiosError: Request failed with status code 401
Call Stack
AxiosError
node_modules/axios/lib/core/AxiosError.js (22:0)
createError
node_modules/langchain/dist/util/axios-fetch-adapter.js (320:0)
settle
node_modules/langchain/dist/util/axios-fetch-adapter.js (25:0)
fetchAdapter/<
node_modules/langchain/dist/util/axios-fetch-adapter.js (175:0)
fetchAdapter
node_modules/langchain/dist/util/axios-fetch-adapter.js (167:0)
```
I have correctly filled all apikey .

**Comment by miurla** [comment]
This error is occurring when requesting OpenAI's API using LangChain.
Could you please check if the OpenAI API key is set correctly?

https://help.openai.com/en/articles/6891767-error-code-401-invalid-authentication

**Comment by miurla** [comment]
If you need assistance, please reopen.
