### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by soundtrackgeek** [miurla/babyagi-ui#4]
Getting this error after inputting my objective and hit the arrow button
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'trim')

error - [RangeError: Invalid status code: 0] {
  code: 'ERR_HTTP_INVALID_STATUS_CODE'

**Comment by virtustate** [comment]
Fresh install a few minutes ago and getting the same error.

**Comment by yoshinorisano** [comment]
I also got the same error…
Did you created an index on Pinecone during setup babyagi-ui?
If not, this error might be fixed by creating an index on Pinecone.
Looking at the screenshot attaced to the issue below might help!
https://github.com/miurla/babyagi-ui/issues/3

**Comment by miurla** [comment]
I apologize for the confusion. We have updated the setup instructions.
https://github.com/miurla/babyagi-ui#-getting-started

As per [yoshinorisano's comment](https://github.com/miurla/babyagi-ui/issues/4#issuecomment-1532150571), could you please try creating the Pinecone index first and then proceed?
