### ISSUE TITLE
"url":"https://serpapi.com/search"},"code":"ERR_BAD_REQUEST","status":401

### ISSUE THREAD

**Issue by findigital** [miurla/babyagi-ui#44]
Error Message - using Vercel for deployment. 

I updated the .env file and entered a working API key for SerpAPI (I know it works since I'm using it for another project). Did I miss somewhere else to configure Serp?

{"message":"Request failed with status code 401","name":"AxiosError","stack":"AxiosError: Request failed with status code 401\n    at settle (file:///var/task/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (file:///var/task/node_modules/axios/lib/adapters/http.js:570:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/1.4.0","Accept-Encoding":"gzip, compress, deflate, br"},"params":{"engine":"google","q":"Research the impact of Generative AI on Retail/eCommerce","num":5},"method":"get","url":"https://serpapi.com/search"},"code":"ERR_BAD_REQUEST","status":401}
![Screen Shot 2023-05-18 at 12 37 19 AM](https://github.com/miurla/babyagi-ui/assets/1157970/35324c60-74c3-4435-9fcf-76b8b09f1bfb)

**Comment by findigital** [comment]
![Screen Shot 2023-05-18 at 12 45 41 AM](https://github.com/miurla/babyagi-ui/assets/1157970/672c1ea5-e3e3-41ce-96ff-fd2ca33c4acf)

**Comment by miurla** [comment]
It seems that the authentication for SerpAPI is failing. In Vercel, you need to set the values in the environment-variables in the settings, not in the env file. Have you set that up? Also, please check if there are any errors in the key.

`https://vercel.com/{your_team}/{project_name}/settings/environment-variables`

**Comment by findigital** [comment]
Like this? @miurla 

<img width="1538" alt="Screen Shot 2023-05-18 at 10 57 28 AM" src="https://github.com/miurla/babyagi-ui/assets/1157970/f6424df6-e462-40de-8b75-1cabd9ad4379">

**Comment by miurla** [comment]
Looks good. Did it not work well with this? 
If the API is deployed and running, you can run the following command in the terminal to check if the search is working properly.

```bash
curl -X POST -H "Content-Type: application/json" -d '{"query":"babyagi"}' https://{project_name}.vercel.app/api/tools/search
```

**Comment by findigital** [comment]
Yes I'm getting good searches thanks!

<img width="1326" alt="Screen Shot 2023-05-18 at 12 34 00 PM" src="https://github.com/miurla/babyagi-ui/assets/1157970/c0f1a882-6ea1-4f87-ac99-3b3b5ef261c2">

**Comment by miurla** [comment]
I'm glad! Please enjoy BabyAGI.
We look forward to your feedback.
