### ISSUE TITLE
Unhandled Runtime Error AxiosError: Request failed with status code 429

### ISSUE THREAD

**Issue by daikitoma** [miurla/babyagi-ui#77]
This prompt appeared when I just set it up and started running. I had no idea what was wrong. Please help me

**Comment by miurla** [comment]
The error is probably from OpenAI's API, and the cause of 429 is "Rate limit reached for requests".

 > Error Code 429 - Rate limit reached for requests

Could you check the following two points?

- You are sharing your API key with other users or applications.
- You are using a free plan that has a low rate limit.

ref: https://help.openai.com/en/articles/6891829-error-code-429-rate-limit-reached-for-requests

**Comment by daikitoma** [comment]
I'm using the free plan. So if I want to use BABYAGI UI then I have to upgreat the plan, right?

**Comment by miurla** [comment]
No, you don't have to move up a plan to use it.
However, there is a usage limit on the free plan, so the question is whether you have reached it.
You can check your usage from the account screen below. Can you check to see if I have reached my usage limit?

https://platform.openai.com/account/usage

Or does the following demo site work fine?
https://babyagi-ui.vercel.app/

**Comment by daikitoma** [comment]
![1685176867876](https://github.com/miurla/babyagi-ui/assets/134763704/51d5f4b9-e132-4132-b72e-620e2ccff703)

**Comment by daikitoma** [comment]
But I can use CHATGPT normally.

**Comment by miurla** [comment]
You will need to set up a paid account as there is no free trial usage on your account.
Please use the `set up a paid account` link on the account screen to set it up and give it a try.
(If you don't have GPT-4 access, the only valid agent is BabyAGI.)

API usage is not associated with ChatGPT.

**Comment by daikitoma** [comment]
It is working！ Thank you very much! Arigatougozaimasu!

**Comment by miurla** [comment]
Glad you solved it. 👍 
Give it a try!
