### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by soundtrackgeek** [miurla/babyagi-ui#8]
TypeError: Cannot read properties of null (reading 'useContext')

This error happened while generating the page. Any console logs will be displayed in the terminal window.

Import trace for requested module:
./node_modules/next/dist/shared/lib/head.js
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
[TypeError: Cannot read properties of null (reading 'useContext')]
[TypeError: Cannot read properties of null (reading 'useContext')]

Happens for a new install and first run

**Comment by miurla** [comment]
The initial setup procedure should not cause this error,
If I clone it again and then do it again, does the same event still occur?

https://github.com/miurla/babyagi-ui#-getting-started

**Comment by miurla** [comment]
If you need assistance, please reopen.
